### ISSUE TITLE
JSON decode error when trying to run the example.

### ISSUE THREAD

**Issue by AndreasPK** [Celeo/Preston#22]
Trying to run this example:

```
from preston import Preston

preston = Preston(
    user_agent='My Character Name'
)

data = preston.get_op('get_characters_character_id', character_id=91316135)
```

I got 

```
(venv) PS C:\Users\andi\Desktop\Eve\api_test> python main.py
Traceback (most recent call last):
  File "C:\Users\andi\Desktop\Eve\api_test\venv\Lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\andi\Desktop\Eve\api_test\main.py", line 7, in <module>
    data = preston.get_op('get_characters_character_id', character_id=91316135)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andi\Desktop\Eve\api_test\preston\preston.py", line 330, in get_op
    path = self._get_path_for_op_id(id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andi\Desktop\Eve\api_test\preston\preston.py", line 248, in _get_path_for_op_id
    for path_key, path_value in self._get_spec()["paths"].items():
                                ^^^^^^^^^^^^^^^^
  File "C:\Users\andi\Desktop\Eve\api_test\preston\preston.py", line 236, in _get_spec
    self.spec = requests.get(self.SPEC_URL.format(self.version)).json()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andi\Desktop\Eve\api_test\venv\Lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

This is using python 3.11 but seems unlikely to matter.

**Comment by Celeo** [comment]
Hi,

Yup, I'm getting it too. I'll take a look.

**Comment by AndreasPK** [comment]
I assume the swagger spec url is wrong. In the debugger I see:

`self.SPEC_URL.format(self.version): 'https://esi.tech.ccp.is/_latest/swagger.json'`

But this site doesn't seem to exist.

I think the current URL is `https://esi.evetech.net` which got me further but then the returned result (both for the example id and one of my character ids) is simply `{'error': 'Not found'}`.

Not sure if I'm doing anything else wrong. I tried a different (post) op as well and got some *got None but expected a kind of stringy thing* error. I assume the reading of the spec doesn't work even with the changed url or something like that.

**Comment by Celeo** [comment]
I just pushed version `4.2.0` to PyPI. Can you grab that and check again? I had to update the base URL.

**Comment by AndreasPK** [comment]
> I just pushed version `4.2.0` to PyPI. Can you grab that and check again? I had to update the base URL.

Seems to work thanks!

**Comment by Celeo** [comment]
You betcha, thanks for reporting!
