### ISSUE TITLE
get empty array

### ISSUE THREAD

**Issue by sergey-koumirov** [Celeo/Preston#7]
**version** = '2.0.1'

```
        preston = Preston()
        system = preston.systems().items.find(name='J105443')
        print( system().stargates )
```

expected: []
got: {'stargates': [], 'securityClass': '', ...}

**Comment by Celeo** [comment]
Yup, looks like a bug.

```
from preston.crest import Preston


preston = Preston()
system = preston.systems().items.find(name='J105443')()
print(type(system)) # <class 'preston.crest.preston.APIElement'>
print(type(system.stargates)) # <class 'preston.crest.preston.APIElement'>
print(system.data == system.stargates.data) # True
```

**Comment by Celeo** [comment]
a4324b0eecaabd667a946913e6cd7d74c8cb04c6 includes a fix for this issue and PyPI has been updated with the new version. Please let me know if you encounter anything else.

**Comment by sergey-koumirov** [comment]
```
        preston = Preston()
        print('---')
        system = preston.systems().items.find(name='Jita')()
        for gate in system.stargates:
            print(gate.name)
        print('---')
        system = preston.systems().items.find(name='J105443')()
        for gate in system.stargates:
            print(gate.name)
        print('---')
```

result 

```
---
Stargate (Maurasi)
Stargate (Perimeter)
Stargate (New Caldari)
Stargate (Sobaseki)
Stargate (Muvolailen)
Stargate (Niyabainen)
Stargate (Ikuchi)
---
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/Users/sergey_koumirov/NonWork/corpfleet/cwo/management/commands/init_map.py", line 25, in handle
    print(gate.name)
AttributeError: 'NoneType' object has no attribute 'name'
```

**Comment by Celeo** [comment]
Well that is ... interesting ....

**Comment by Celeo** [comment]
This was a fun trip into Python's internals for `__getitem__` versus `__iter__`. I've committed a fix in fd52d90d7ac4967e0138faedcadbb190cf04bc4b and have update PyPI. I'll leave this issue open - let me know if I missed something.

**Comment by sergey-koumirov** [comment]
works for me

**Comment by Celeo** [comment]
Excellent! Thanks for reporting.
